Repository BeHelp/BeHelp, pull requests merged in 2022-01, with the labels that each got.

#146 Register form
  frontend/src/assets/fas/camera-solid.svg
  frontend/src/components/Header.vue
  frontend/src/components/Register.vue
  frontend/src/components/styles/abstract/_base.scss
  frontend/src/components/styles/layout/_header.scss
  frontend/src/components/styles/layout/_register.scss
  frontend/src/components/styles/layout/_search.scss
Labels: html, css

#147 refactored & improved backend login & JWT code
  backend/business-logic/login.js
  backend/controllers/login.js
  backend/middleware/auth-check.js
  backend/server.js
  package-lock.json
  package.json
Labels: enhancement, database, backend, business-logic, controllers, routes

#148 refreshtoken route and functionality added
  backend/business-logic/login.js
  backend/business-logic/users.js
  backend/controllers/login.js
  backend/data-access/db.js
  backend/middleware/auth-check.js
  backend/models/RefreshToken.js
  backend/server.js
  frontend/src/assets/js/font-awesome.js
  frontend/src/main.js
  frontend/src/store/index.js
  frontend/src/views/Login.vue
  package-lock.json
  package.json
Labels: backend

#153 Register form – select multiple languages
  frontend/src/components/Register.vue
  package-lock.json
Labels: html, css, test

#158 Cards draft 1
  .vscode/settings.json
  frontend/src/App.vue
  frontend/src/assets/img/volunteer-1.svg
  frontend/src/assets/img/volunteer-2.svg
  frontend/src/assets/logos/geo__logo.svg
  frontend/src/components/Card.vue
  frontend/src/components/Cardversion.vue
  frontend/src/components/Search.vue
  frontend/src/components/styles/layout/_card.scss
  frontend/src/main.js
  frontend/src/views/Volunteers.vue
  package-lock.json
Labels: cards

#162 logout for backend & frontend
  backend/business-logic/login.js
  backend/business-logic/users.js
  backend/controllers/users.js
  backend/middleware/auth.js
  backend/routes/users.js
  backend/server.js
  frontend/src/components/Header.vue
  frontend/src/components/styles/layout/_header.scss
  frontend/src/store/index.js
  frontend/src/views/Login.vue
Labels: database, html, css, backend, business-logic, controllers, routes

#154 email service added to backend API on /email route
  backend/controllers/email.js
  backend/routes/email.js
  backend/server.js
  package-lock.json
  package.json
Labels: backend

#160 dropdown scss style added & register form city selection added
  frontend/src/assets/js/ignore.css
  frontend/src/assets/js/ignore.js
  frontend/src/assets/jsondata/genders.json
  frontend/src/assets/jsondata/skills.json
  frontend/src/components/Register.vue
  frontend/src/components/Search.vue
  frontend/src/components/styles/layout/_dropdown.scss
  frontend/src/components/styles/layout/_register.scss
  frontend/src/views/Volunteers.vue
Labels: html, css

#164 changed search bar to have single select & be more responsive
  frontend/src/components/Search.vue
  frontend/src/components/styles/layout/_header.scss
  frontend/src/components/styles/layout/_search.scss
Labels: html, css

#128 feature: Thankyou page linked to routes
  .gitignore
  backend/.gitignore
  backend/package.json
  frontend/src/components/styles/layout/_thankyou.scss
  frontend/src/views/Contacts.vue
  frontend/src/views/Thankyou.vue
Labels: question, html, css

#166 fix: search bar & single select filtering
  frontend/src/components/Search.vue
Labels: vue-js

#167 feature: nicer user notifications
  frontend/src/App.vue
  frontend/src/components/styles/abstract/_base.scss
  frontend/src/main.js
  frontend/src/views/Login.vue
  package-lock.json
  package.json
Labels: html, css

#175 fix: search bar saves state & redirects to volunteer page from home page
  frontend/index.html
  frontend/src/components/Search.vue
  frontend/src/store/index.js
  frontend/src/views/Volunteers.vue
  package-lock.json
Labels: vue-js

#181 fix: logout refactoring to async-await
  frontend/src/components/Header.vue
Labels: vue-js

#183 feature: Deployment wit Procfile
  .env.development
  .env.production
  Procfile
  backend/server.js
  frontend/src/components/Header.vue
  frontend/src/components/Search.vue
  frontend/src/views/Login.vue
  package-lock.json
  package.json
Labels: deployment

#174 feature: myProfile component
  backend/business-logic/register.js
  backend/controllers/register.js
  backend/routes/register.js
  frontend/src/components/Profile.vue
  frontend/src/components/styles/layout/_profile.scss
  frontend/src/router/index.js
  frontend/src/views/Myprofile.vue
  package-lock.json
Labels: design, html, css

#188 Feature: Myprofile - Delete
  .vscode/settings.json
  backend/business-logic/register.js
  backend/controllers/register.js
  backend/routes/register.js
  backend/server.js
  frontend/src/components/Card.vue
  frontend/src/components/Profile.vue
  frontend/src/components/Search.vue
  frontend/src/components/styles/abstract/_variables.scss
  frontend/src/components/styles/layout/_card.scss
  frontend/src/components/styles/layout/_search.scss
  frontend/src/views/Volunteers.vue
  package-lock.json
Labels: backend, delete

#173 feature: registration form logic
  backend/controllers/register.js
  backend/models/User.js
  frontend/src/assets/js/cloudinary.js
  frontend/src/assets/jsondata/cities.json
  frontend/src/assets/jsondata/genders.json
  frontend/src/assets/jsondata/languages.json
  frontend/src/components/Register.vue
  frontend/src/components/styles/abstract/_variables.scss
  frontend/src/components/styles/layout/_register.scss
  package-lock.json
Labels: html, css, business-logic

#192 update: readme.md documentation updated to reflect the presentation content
  README.md
Labels: documentation

#189 feature:update profile - backend logic
  README.md
  backend/business-logic/users.js
  backend/controllers/users.js
  backend/models/User.js
  backend/routes/users.js
  backend/server.js
  frontend/src/assets/jsondata/languages.json
  frontend/src/assets/jsondata/skills.json
  frontend/src/assets/translations/ar.json
  frontend/src/assets/translations/en.json
  frontend/src/assets/translations/esp.json
  frontend/src/assets/translations/fr.json
  frontend/src/assets/translations/nl.json
  frontend/src/components/Card.vue
  frontend/src/components/Cardversion.vue
  frontend/src/components/Filter.vue
  frontend/src/components/Footer.vue
  frontend/src/components/Hamburger.vue
  frontend/src/components/Header.vue
  frontend/src/components/Profile.vue
  frontend/src/components/Pswdrecovery.vue
  frontend/src/components/Register.vue
  frontend/src/components/Search-test.vue
  frontend/src/components/Search.vue
  frontend/src/components/Services.vue
  frontend/src/components/Testimony.vue
  frontend/src/components/Whoarewe.vue
  frontend/src/components/styles/layout/_about.scss
  frontend/src/components/styles/layout/_card.scss
  frontend/src/components/styles/layout/_contact.scss
  frontend/src/components/styles/layout/_dropdown.scss
  frontend/src/components/styles/layout/_footer.scss
  frontend/src/components/styles/layout/_hamburger.scss
  frontend/src/components/styles/layout/_header.scss
  frontend/src/components/styles/layout/_profile.scss
  frontend/src/components/styles/layout/_pswdrecovery.scss
  frontend/src/components/styles/layout/_register.scss
  frontend/src/components/styles/layout/_search.scss
  frontend/src/components/styles/layout/_services.scss
  frontend/src/components/styles/layout/_testimony.scss
  frontend/src/components/styles/layout/_volunteerContact.scss
  frontend/src/components/styles/layout/_whoarewe.scss
  frontend/src/components/styles/style.scss
  frontend/src/views/About.vue
  frontend/src/views/Contacts.vue
  frontend/src/views/Home.vue
  frontend/src/views/Signup.vue
  frontend/src/views/VolunteerContact.vue
  frontend/src/views/Volunteers.vue
  package-lock.json
Labels: backend, business-logic

#201 FIX: env.production variable URL fixed to herokuapp.com instead of heroku.com
  .env.production
Labels: deployment

#204 FIX: City* fixed in search bar for all languages & env.production
  .env.production
  frontend/src/assets/translations/ar.json
  frontend/src/assets/translations/en.json
  frontend/src/assets/translations/esp.json
  frontend/src/assets/translations/fr.json
  frontend/src/assets/translations/nl.json
  frontend/src/components/Register.vue
Labels: FIX

#205 FIX: Footer fix
  frontend/src/components/Footer.vue
Labels: FIX

#208 fix:usermenu list
  frontend/src/components/Footer.vue
  frontend/src/components/Header.vue
Labels: FIX

#207 FIX: fixed autofill color to grey in forms
  frontend/src/components/styles/layout/_register.scss
Labels: FIX

#210 FIX: services icon fix to figma
  frontend/src/components/Services.vue
  frontend/src/components/styles/layout/_services.scss
  package-lock.json
  package.json
Labels: FIX

#209 FIX: tech tools documentation
  README.md
Labels: FIX

#213 fix3, fix4 / removed persistedstate & nice search notification
  frontend/src/components/Search.vue
  frontend/src/store/index.js
Labels: FIX

#214 fix: showing all volunteers if on volunteers page
  frontend/src/components/Search.vue
Labels: FIX

#212 fix volunteer registration
  frontend/src/components/Register.vue
Labels: FIX

#215 fix: adding cloudinary & iconify URLs to CSP policy in server.js
  backend/server.js
Labels: deployment, FIX

#217 fix: emailJS added to CSP policy
  backend/server.js
Labels: deployment, FIX

#218 fix:skills and description - hidden for newcomers
  backend/business-logic/users.js
  backend/controllers/users.js
  frontend/src/components/Profile.vue
Labels: FIX

#219 fixed CSS login&header&search
  frontend/src/assets/homepage-search.jpg
  frontend/src/components/Search.vue
  frontend/src/components/styles/layout/_header.scss
  frontend/src/components/styles/layout/_login.scss
  frontend/src/components/styles/layout/_search.scss
Labels: FIX

#220 fix: newcomer saved to DB correctly
  frontend/src/components/Register.vue
Labels: FIX

#222 fix: photo icon & firstName in header updates after myprofile update
  frontend/src/components/Profile.vue
  frontend/src/store/index.js
Labels: FIX

#221 FIX:responsive register form
  frontend/src/components/Register.vue
  frontend/src/components/styles/layout/_register.scss
Labels: FIX

#225 youtube video demo added to readme.md
  README.md
Labels: documentation
